INSERT INTO `permissions` VALUES (1, 'category', 'Authorization for Creating Categories', NULL, NULL);
INSERT INTO `permissions` VALUES (2, 'restaurant_add', 'Authorization	for Creating Restaurants', NULL, NULL);
INSERT INTO `permissions` VALUES (3, 'restaurant_edit', 'Authorization	for Editing Restaurants', NULL, NULL);
INSERT INTO `permissions` VALUES (4, 'restaurant_remove', 'Authorization	for Deleting Restaurants', NULL, NULL);
INSERT INTO `permissions` VALUES (5, 'menu_add', 'Authorization for Creating Restaurants Menu and their pricing and discount price', NULL, NULL);
INSERT INTO `permissions` VALUES (6, 'menu_edit', 'Authorization for Editing Restaurants Menu and their pricing and discount price', NULL, NULL);
INSERT INTO `permissions` VALUES (7, 'menu_remove', 'Authorization for Deleting Restaurants Menu and their pricing and discount price', NULL, NULL);
INSERT INTO `permissions` VALUES (8, 'owner_activity', 'Authorization for restaurant owner activity', NULL, NULL);
INSERT INTO `permissions` VALUES (9, 'owner_add', 'Authorization for Creating restaurant Owners', NULL, NULL);
INSERT INTO `permissions` VALUES (10, 'owner_edit', 'Authorization for Editing restaurant Owners', NULL, NULL);
INSERT INTO `permissions` VALUES (11, 'owner_remove', 'Authorization for Deleting restaurant Owners', NULL, NULL);
INSERT INTO `permissions` VALUES (12, 'driver_add', 'Authorization for Creating Drivers', NULL, NULL);
INSERT INTO `permissions` VALUES (13, 'driver_edit', 'Authorization for Editing Drivers', NULL, NULL);
INSERT INTO `permissions` VALUES (14, 'driver_remove', 'Authorization for Deleting Drivers', NULL, NULL);
INSERT INTO `permissions` VALUES (15, 'user_add', 'Authorization for Creating Users', NULL, NULL);
INSERT INTO `permissions` VALUES (16, 'user_edit', 'Authorization for Editing Users', NULL, NULL);
INSERT INTO `permissions` VALUES (17, 'user_remove', 'Authorization for Deleting Users', NULL, NULL);
INSERT INTO `permissions` VALUES (18, 'advertisement', 'Authorization	for	advertising	management', NULL, NULL);
INSERT INTO `permissions` VALUES (19, 'o_message', 'Authorization	for	sending	messages to restaurant owners', NULL, NULL);
INSERT INTO `permissions` VALUES (20, 'u_message', 'Authorization for sending	messages to users', NULL, NULL);
